-- Add missing language columns for community_threads
ALTER TABLE public.community_threads
ADD COLUMN IF NOT EXISTS title_es TEXT,
ADD COLUMN IF NOT EXISTS title_fr TEXT,
ADD COLUMN IF NOT EXISTS title_de TEXT,
ADD COLUMN IF NOT EXISTS title_zh TEXT,
ADD COLUMN IF NOT EXISTS title_ko TEXT,
ADD COLUMN IF NOT EXISTS title_it TEXT,
ADD COLUMN IF NOT EXISTS title_ru TEXT,
ADD COLUMN IF NOT EXISTS title_ar TEXT,
ADD COLUMN IF NOT EXISTS title_hi TEXT,
ADD COLUMN IF NOT EXISTS content_es TEXT,
ADD COLUMN IF NOT EXISTS content_fr TEXT,
ADD COLUMN IF NOT EXISTS content_de TEXT,
ADD COLUMN IF NOT EXISTS content_zh TEXT,
ADD COLUMN IF NOT EXISTS content_ko TEXT,
ADD COLUMN IF NOT EXISTS content_it TEXT,
ADD COLUMN IF NOT EXISTS content_ru TEXT,
ADD COLUMN IF NOT EXISTS content_ar TEXT,
ADD COLUMN IF NOT EXISTS content_hi TEXT;

-- Add missing language columns for community_posts
ALTER TABLE public.community_posts
ADD COLUMN IF NOT EXISTS content_es TEXT,
ADD COLUMN IF NOT EXISTS content_fr TEXT,
ADD COLUMN IF NOT EXISTS content_de TEXT,
ADD COLUMN IF NOT EXISTS content_zh TEXT,
ADD COLUMN IF NOT EXISTS content_ko TEXT,
ADD COLUMN IF NOT EXISTS content_it TEXT,
ADD COLUMN IF NOT EXISTS content_ru TEXT,
ADD COLUMN IF NOT EXISTS content_ar TEXT,
ADD COLUMN IF NOT EXISTS content_hi TEXT;